services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}
    expose:
      - 5432

  web:
    build:
      dockerfile: ./web/build/Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
    ports:
      - "0.0.0.0:8002:8000"

    develop:
      watch:
        - path: web/
          action: sync # the code will be rebuilt by django StatReloader
          target: /app/

volumes:
  db_data:
