version: '3'

services:
  postgres:  # TODO: add an external data directory
    build:
      dockerfile: ./build/postgres/Dockerfile
      context: .
    volumes:
      - ./db_data:/var/lib/postgresql/data
    expose:
      - 5432

  web:
    build:
      dockerfile: ./build/web/Dockerfile
      context: .
    depends_on:
      - postgres
    command:
      - "/bin/bash"
      - "-c"
      - "/app/entry_point.sh"
    ports:
      - "0.0.0.0:8002:8000"