# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 15:40
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_sender', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IdentifiedNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('general_location', models.CharField(max_length=70, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='KiambuConstituencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('const_nam', models.CharField(max_length=50)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('population', models.IntegerField()),
                ('pop_densty', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='KiambuCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_0', models.IntegerField()),
                ('iso', models.CharField(max_length=254)),
                ('name_0', models.CharField(max_length=254)),
                ('id_1', models.IntegerField()),
                ('name_1', models.CharField(max_length=254)),
                ('id_2', models.IntegerField()),
                ('name_2', models.CharField(max_length=254)),
                ('varname_2', models.CharField(max_length=254)),
                ('nl_name_2', models.CharField(max_length=254)),
                ('hasc_2', models.CharField(max_length=254)),
                ('cc_2', models.CharField(max_length=254)),
                ('type_2', models.CharField(max_length=254)),
                ('engtype_2', models.CharField(max_length=254)),
                ('validfr_2', models.CharField(max_length=254)),
                ('validto_2', models.CharField(max_length=254)),
                ('remarks_2', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='KiambuDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_0', models.IntegerField()),
                ('iso', models.CharField(max_length=254)),
                ('name_0', models.CharField(max_length=254)),
                ('id_1', models.IntegerField()),
                ('name_1', models.CharField(max_length=254)),
                ('id_2', models.IntegerField()),
                ('name_2', models.CharField(max_length=254)),
                ('id_3', models.IntegerField()),
                ('name_3', models.CharField(max_length=254)),
                ('varname_3', models.CharField(max_length=254)),
                ('nl_name_3', models.CharField(max_length=254)),
                ('hasc_3', models.CharField(max_length=254)),
                ('type_3', models.CharField(max_length=254)),
                ('engtype_3', models.CharField(max_length=254)),
                ('validfr_3', models.CharField(max_length=254)),
                ('validto_3', models.CharField(max_length=254)),
                ('remarks_3', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='KiambuLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_0', models.IntegerField()),
                ('iso', models.CharField(max_length=254)),
                ('name_0', models.CharField(max_length=254)),
                ('id_1', models.IntegerField()),
                ('name_1', models.CharField(max_length=254)),
                ('id_2', models.IntegerField()),
                ('name_2', models.CharField(max_length=254)),
                ('id_3', models.IntegerField()),
                ('name_3', models.CharField(max_length=254)),
                ('id_4', models.IntegerField()),
                ('name_4', models.CharField(max_length=254)),
                ('varname_4', models.CharField(max_length=254)),
                ('type_4', models.CharField(max_length=254)),
                ('engtype_4', models.CharField(max_length=254)),
                ('validfr_4', models.CharField(max_length=254)),
                ('validto_4', models.CharField(max_length=254)),
                ('remarks_4', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='KiambuSublocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_0', models.IntegerField()),
                ('iso', models.CharField(max_length=254)),
                ('name_0', models.CharField(max_length=254)),
                ('id_1', models.IntegerField()),
                ('name_1', models.CharField(max_length=254)),
                ('id_2', models.IntegerField()),
                ('name_2', models.CharField(max_length=254)),
                ('id_3', models.IntegerField()),
                ('name_3', models.CharField(max_length=254)),
                ('id_4', models.IntegerField()),
                ('name_4', models.CharField(max_length=254)),
                ('id_5', models.IntegerField()),
                ('name_5', models.CharField(max_length=254)),
                ('type_5', models.CharField(max_length=254)),
                ('engtype_5', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyWeatherByCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('boston_temp', models.DecimalField(decimal_places=1, max_digits=5)),
                ('houston_temp', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('id_number', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('receipt_number', models.IntegerField()),
                ('date_of_payment', models.DateField()),
                ('paid_by', models.CharField(max_length=50)),
                ('paid_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.OwnershipInfo')),
            ],
        ),
        migrations.CreateModel(
            name='RatesPayable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_from', models.CharField(max_length=50)),
                ('parcel_no', models.CharField(max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shamba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(null=True)),
                ('objectid_1', models.IntegerField()),
                ('objectid', models.IntegerField()),
                ('shape_leng', models.FloatField()),
                ('y_coordina', models.IntegerField()),
                ('x_coordina', models.IntegerField()),
                ('perimeter', models.IntegerField()),
                ('parcel_no', models.IntegerField()),
                ('owner', models.CharField(max_length=254)),
                ('soil_type', models.CharField(max_length=254)),
                ('state', models.CharField(max_length=254)),
                ('cost_value', models.IntegerField()),
                ('pic_url', models.CharField(max_length=254)),
                ('electricit', models.CharField(max_length=254)),
                ('water', models.CharField(max_length=254)),
                ('outlinetra', models.FloatField()),
                ('shape_le_1', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('type_of_lease', models.CharField(choices=[(b'Freehold', b'Free-hold'), (b'Leasehold', b'Leasehold')], max_length=20, null=True)),
                ('zone', models.CharField(choices=[(b'Industrial', b'Industrial'), (b'Commercial', b'Commercial'), (b'Residential', b'Residential')], max_length=20, null=True)),
                ('period_of_lease', models.IntegerField(null=True)),
                ('land_use', models.CharField(choices=[(b'Agricultural', b'Agricultural'), (b'Bare_Land', b'Bare_Land')], max_length=20, null=True)),
                ('shamba_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.OwnershipInfo')),
            ],
        ),
    ]
