# -*- coding: utf-8 -*-
# Generated by Victor on 2023-05-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial')
    ]
    operations = [
        migrations.RemoveField('KiambuCounty', 'varname_2'),
        migrations.RemoveField('KiambuCounty', 'nl_name_2'),
        migrations.RemoveField('KiambuCounty', 'cc_2'),
        migrations.RemoveField('KiambuCounty', 'remarks_2'),
        migrations.AlterField('KiambuConstituencies', 'population', models.IntegerField(null=True)),
        migrations.AlterField('KiambuConstituencies', 'pop_densty', models.IntegerField(null=True)),
        migrations.AlterField('Shamba', 'pic_url', models.CharField(null=True)),
        migrations.AlterField('Shamba', 'electricit', models.CharField(null=True)),
        migrations.AlterField('Shamba', 'water', models.CharField(null=True)),
    ]
