# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KiambuCounty',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('id_0', models.IntegerField()),
                ('iso', models.CharField(max_length=254)),
                ('name_0', models.CharField(max_length=254)),
                ('id_1', models.IntegerField()),
                ('name_1', models.CharField(max_length=254)),
                ('id_2', models.IntegerField()),
                ('name_2', models.CharField(max_length=254)),
                ('varname_2', models.CharField(max_length=254)),
                ('nl_name_2', models.CharField(max_length=254)),
                ('hasc_2', models.CharField(max_length=254)),
                ('cc_2', models.CharField(max_length=254)),
                ('type_2', models.CharField(max_length=254)),
                ('engtype_2', models.CharField(max_length=254)),
                ('validfr_2', models.CharField(max_length=254)),
                ('validto_2', models.CharField(max_length=254)),
                ('remarks_2', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='KiambuDivision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('id_0', models.IntegerField()),
                ('iso', models.CharField(max_length=254)),
                ('name_0', models.CharField(max_length=254)),
                ('id_1', models.IntegerField()),
                ('name_1', models.CharField(max_length=254)),
                ('id_2', models.IntegerField()),
                ('name_2', models.CharField(max_length=254)),
                ('id_3', models.IntegerField()),
                ('name_3', models.CharField(max_length=254)),
                ('varname_3', models.CharField(max_length=254)),
                ('nl_name_3', models.CharField(max_length=254)),
                ('hasc_3', models.CharField(max_length=254)),
                ('type_3', models.CharField(max_length=254)),
                ('engtype_3', models.CharField(max_length=254)),
                ('validfr_3', models.CharField(max_length=254)),
                ('validto_3', models.CharField(max_length=254)),
                ('remarks_3', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='KiambuLocation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('id_0', models.IntegerField()),
                ('iso', models.CharField(max_length=254)),
                ('name_0', models.CharField(max_length=254)),
                ('id_1', models.IntegerField()),
                ('name_1', models.CharField(max_length=254)),
                ('id_2', models.IntegerField()),
                ('name_2', models.CharField(max_length=254)),
                ('id_3', models.IntegerField()),
                ('name_3', models.CharField(max_length=254)),
                ('id_4', models.IntegerField()),
                ('name_4', models.CharField(max_length=254)),
                ('varname_4', models.CharField(max_length=254)),
                ('type_4', models.CharField(max_length=254)),
                ('engtype_4', models.CharField(max_length=254)),
                ('validfr_4', models.CharField(max_length=254)),
                ('validto_4', models.CharField(max_length=254)),
                ('remarks_4', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='KiambuSublocation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('id_0', models.IntegerField()),
                ('iso', models.CharField(max_length=254)),
                ('name_0', models.CharField(max_length=254)),
                ('id_1', models.IntegerField()),
                ('name_1', models.CharField(max_length=254)),
                ('id_2', models.IntegerField()),
                ('name_2', models.CharField(max_length=254)),
                ('id_3', models.IntegerField()),
                ('name_3', models.CharField(max_length=254)),
                ('id_4', models.IntegerField()),
                ('name_4', models.CharField(max_length=254)),
                ('id_5', models.IntegerField()),
                ('name_5', models.CharField(max_length=254)),
                ('type_5', models.CharField(max_length=254)),
                ('engtype_5', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Shamba',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('objectid_1', models.IntegerField()),
                ('objectid', models.IntegerField()),
                ('shape_leng', models.FloatField()),
                ('y_coordina', models.IntegerField()),
                ('x_coordina', models.IntegerField()),
                ('perimeter', models.IntegerField()),
                ('parcel_no', models.IntegerField()),
                ('owner', models.CharField(max_length=254)),
                ('soil_type', models.CharField(max_length=254)),
                ('state', models.CharField(max_length=254)),
                ('cost_value', models.IntegerField()),
                ('pic_url', models.CharField(max_length=254)),
                ('electricit', models.CharField(max_length=254)),
                ('water', models.CharField(max_length=254)),
                ('outlinetra', models.FloatField()),
                ('shape_le_1', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
